### ISSUE TITLE
`POST /application/{client_id}/token` does not support clientId/clientSecret basic authentication.

### ISSUE THREAD

**Issue by kpeters-cbsi** [octokit/auth-oauth-app.js#170]
I am attempting to create a sketch, below, of the OAuth token verification process based on the README. When I run the sketch, however, I get the following error message. Am I doing something wrong, or is there an error in the README?

```
Error: [@octokit/auth-oauth-app] "POST /application/{client_id}/token" does not support clientId/clientSecret basic authentication. Use @octokit/auth-oauth-user instead.
    at hook (/home/kit/work/sketches/js/github-app/node_modules/@octokit/auth-oauth-app/dist-node/index.js:141:11)
    at /home/kit/work/sketches/js/github-app/node_modules/before-after-hook/lib/register.js:25:15
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
    at async /home/kit/work/sketches/js/github-app/verify-token.js:25:5
```

Code:
```javascript
const { Octokit } = require("@octokit/core");
const {
  createOAuthAppAuth,
  createOAuthUserAuth,
} = require("@octokit/auth-oauth-app");

// These are placeholder values, not the actual values I'm using
const clientId: "1234567890abcdef1234"; 
const clientSecret: "1234567890abcdef1234567890abcdef12345678";

const token = process.argv[2];
if (!token) {
  console.error('No token supplied');
  process.exit(-1);
}

(async function() {
    const octokit = new Octokit({
      authStrategy: createOAuthAppAuth,
      auth: {
        clientId,
        clientSecret,
      },
  });

  await octokit.request('POST /application/{client_id}/token', {
    client_id: clientId,
    access_token: token
  })
  console.log('Token is OK')
}())
```

**Comment by gr2m** [comment]
I'll look into this shortly. Thank you for the solid bug report 👍🏼

**Comment by gr2m** [comment]
Here is a reproducible test case:

https://runkit.com/gr2m/octokit-auth-oauth-app-js-170

`OAUTH_TEST_TOKEN` needs to be a token that was created by the OAuth App defined in `OAUTH_TEST_CLIENT_ID`/`OAUTH_TEST_CLIENT_SECRET`

**Comment by gr2m** [comment]
You have a slight typo.

```diff
- await octokit.request('POST /application/{client_id}/token', {
+ await octokit.request('POST /applications/{client_id}/token', {
    client_id: clientId,
    access_token: token
  })
```

See https://docs.github.com/en/rest/reference/apps#check-a-token

Let me know if that fixes the problem for you.

By the way we also have a helper method to check a token for validity:
https://github.com/octokit/oauth-methods.js/#checktoken

And we have a whole SDK for OAuth apps: 
https://github.com/octokit/oauth-app.js#readme

The code works with the fix:
https://runkit.com/gr2m/octokit-auth-oauth-app-js-170/2.0.0

**Comment by kpeters-cbsi** [comment]
> 
> 
> You have a slight typo.
> 
> ```diff
> - await octokit.request('POST /application/{client_id}/token', {
> + await octokit.request('POST /applications/{client_id}/token', {
>     client_id: clientId,
>     access_token: token
>   })
> ```
> 
> See https://docs.github.com/en/rest/reference/apps#check-a-token
> 
> Let me know if that fixes the problem for you.
> 
> By the way we also have a helper method to check a token for validity:
> https://github.com/octokit/oauth-methods.js/#checktoken
> 
> And we have a whole SDK for OAuth apps:
> https://github.com/octokit/oauth-app.js#readme
> 
> The code works with the fix:
> https://runkit.com/gr2m/octokit-auth-oauth-app-js-170/2.0.0

Fixing the typo fixes my problem, thanks! And thank you for the heads-up regarding `oauth-methods`.
