### ISSUE TITLE
publish new version?

### ISSUE THREAD

**Issue by larshp** [octokit/auth-oauth-app.js#219]
Hi,
Consider releasing a new version? the latest release uses node-fetch@2.6.5 which has the following vulnerbility,

```
node-fetch  <2.6.7
Severity: high
node-fetch is vulnerable to Exposure of Sensitive Information to an Unauthorized Actor - https://github.com/advisories/GHSA-r683-j2x4-v87g
```

```
$ npm ls node-fetch
└─┬ @octokit/auth-oauth-app@4.3.0
  └─┬ @octokit/request@5.6.2
    └── node-fetch@2.6.5
```

**Comment by wolfy1339** [comment]
There isn't a need to publish a new version.

You can simply bump `@octokit/request` and `node-fetch` in your `package-lock.json`

It may be easier to just publish a new version anyways
