### ISSUE TITLE
broken node 10/12 compatibility

### ISSUE THREAD

**Issue by raptordzuricsko** [octokit/auth-oauth-app.js#240]
Hi, i believe upgrading to octokit/requests 6 dropped old Node support similar to this issue https://github.com/octokit/app.js/issues/296 . Can you release a new patch version that supports the old node version when you have a chance, and release dropping node 10/12 support as a major version so that it doesn't automatically get picked up?

I can fill in some more details if this is vague, will be back online tonight/tomorrow

**Comment by wolfy1339** [comment]
Sorry about that. Again.

Things are hectic when you're handling this many packages, as you can probably see.

This will have to wait until #237 is merged, as I believe that will be the easiest way to handle it. Can you pin the dependency for now

**Comment by raptordzuricsko** [comment]
hey no worries. thank you for developing on this stuff! We tried a couple strategies to lock down dependencies but it’s difficult because it’s a transitive dependency. compounded by us stuck on an old yarn version(so theres issues with using certain fields in package.json). i can take a look tomorrow to see if there’s anything else we didn’t think of too

**Comment by raptordzuricsko** [comment]
We are forking our old ci tool(brigade v1) to see if we can upgrade node on it, as well as seeing if we can publish a forked version of octokit with the version locked down.

**Comment by raptordzuricsko** [comment]
forking our legacy tool seemed to work so far actually! So we are much less urgent.

**Comment by wolfy1339** [comment]
The new release should be cut with the fix real soon

**Comment by wolfy1339** [comment]
It see

**Comment by wolfy1339** [comment]
We released a major version. I'll see what I can do for you

**Comment by raptordzuricsko** [comment]
thank you so much! Our node version upgrade was successful and i'm happy to close.
