### ISSUE TITLE
token reset: check for new endpoint

### ISSUE THREAD

**Issue by gr2m** [octokit/auth-oauth-app.js#36]
When a token is reset, we update the internally cached token 

https://github.com/octokit/auth-oauth-app.js/blob/4c31c42a2c7f7b7347e39c002be88b8bd1811840/src/hook.ts#L46-L54

However, we do not check for the new route:
https://developer.github.com/v3/apps/oauth_applications/#reset-a-token

**Comment by romanbalayan** [comment]
@gr2m 
Was about to get this, but it seems like it's already currently handled? 

`
const parsedEndpoint = request.endpoint.parse(endpoint);
    // `POST /applications/:client_id/tokens/:access_token` (legacy) or
    // `PATCH /applications/:client_id/token` resets the passed token
    // and returns a new one. If that’s the current request then update internal state.
    const isLegacyTokenResetRequest =
      endpoint.method === "POST" &&
      /^\/applications\/:?[\w_]+\/tokens\/:?[\w_]+$/.test(endpoint.url);
    const isTokenResetRequest =
      endpoint.method === "PATCH" &&
      /^\/applications\/:?[\w_]+\/token$/.test(endpoint.url);

    if (isLegacyTokenResetRequest || isTokenResetRequest) {
      state.token = {
        token: response.data.token,
        // @ts-ignore figure this out
        scope: response.data.scopes
      };
    }
`

**Comment by gr2m** [comment]
Indeed, thanks a lot for looking into it @romanbalayan! It looks like it was resolved via https://github.com/octokit/auth-oauth-app.js/pull/41
