### ISSUE TITLE
Increasing the unauthenticated rate limit with Octokit 17

### ISSUE THREAD

**Issue by znarf** [octokit/auth-oauth-app.js#43]
We would like to increase our rate limit as specified here:
https://developer.github.com/v3/#increasing-the-unauthenticated-rate-limit-for-oauth-applications It seems it's not deprecated right?

We used to pass `clientId` and `clientSecret` in `auth` but that has been deprecated in Octokit.
We tried `@octokit/auth-basic` and `@octokit/auth-oauth-app` without success as they both try to exchange with a token.

What simple solution would you recommend?

**Comment by gr2m** [comment]
I'm fairly sure v3.0.1 will resolve the problem for you. Could you give it a try please?

**Comment by znarf** [comment]
@gr2m brilliant, thank you! I will try tomorrow.
